namespace SeaBattle
{
    partial class MainForm
    {
        /// <summary>
        /// Required constructor variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Release all used resources.
        /// </summary>
        /// <param name="disposing">true if the managed resource is to be disposed of; otherwise false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code automatically generated by Windows Form Designer

        /// <summary>
        /// Required method for constructor support - do not change
        /// contents of this method using the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            this.button4x = new System.Windows.Forms.Button();
            this.button3x = new System.Windows.Forms.Button();
            this.button2x = new System.Windows.Forms.Button();
            this.button1x = new System.Windows.Forms.Button();
            this.label2x = new System.Windows.Forms.Label();
            this.label3x = new System.Windows.Forms.Label();
            this.label4x = new System.Windows.Forms.Label();
            this.labelYourField = new System.Windows.Forms.Label();
            this.labelEnemyField = new System.Windows.Forms.Label();
            this.labelStatus = new System.Windows.Forms.Label();
            this.buttonRestart = new System.Windows.Forms.Button();
            this.labelComputerMove = new System.Windows.Forms.Label();
            this.label1x = new System.Windows.Forms.Label();
            this.contextMenuStrip = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.GameRestartToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ComputerMovesSpeedToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.SlowlyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.AverageToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.RapidlyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.InstantlyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.MarkComputerMovesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.buttonRotate = new System.Windows.Forms.Button();
            this.comboBoxComputerMoveSpeed = new System.Windows.Forms.ComboBox();
            this.buttonGameStart = new System.Windows.Forms.Button();
            this.labelShipsPlaceLeft = new System.Windows.Forms.Label();
            this.labelPlaceShips = new System.Windows.Forms.Label();
            this.progressBar = new System.Windows.Forms.ProgressBar();
            this.labelComputerMovingSpeed = new System.Windows.Forms.Label();
            this.panel = new System.Windows.Forms.Panel();
            this.materialLabelPlace = new MaterialSkin.Controls.MaterialLabel();
            this.RaisedButtonRotate = new MaterialSkin.Controls.MaterialRaisedButton();
            this.FlatButtonRotate = new MaterialSkin.Controls.MaterialFlatButton();
            this.RandomArangeShip = new MaterialSkin.Controls.MaterialRaisedButton();
            this.materialLabelplaceship = new MaterialSkin.Controls.MaterialLabel();
            this.groupBoxEnemy = new System.Windows.Forms.GroupBox();
            this.checkrandommoves = new MaterialSkin.Controls.MaterialCheckBox();
            this.checkBoxEnemyRandomMoves = new System.Windows.Forms.CheckBox();
            this.MarkenemyMoves = new MaterialSkin.Controls.MaterialCheckBox();
            this.buttonArrangeShipsRandomly = new System.Windows.Forms.Button();
            this.labelPrompt = new System.Windows.Forms.Label();
            this.materialContextMenuStrip1 = new MaterialSkin.Controls.MaterialContextMenuStrip();
            this.перезапуститьИгруToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.скоростьХодаКомпьютераToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.медленнаяToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.средняяToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.быстраяToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.мгновеннаяToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.помечатьШагиToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.выходToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.materialLabelyourfield = new MaterialSkin.Controls.MaterialLabel();
            this.materialSingleLineTextField1 = new MaterialSkin.Controls.MaterialSingleLineTextField();
            this.materialLabelenemyField = new MaterialSkin.Controls.MaterialLabel();
            this.materialButtonRestart = new MaterialSkin.Controls.MaterialRaisedButton();
            this.materialProgressBar1 = new MaterialSkin.Controls.MaterialProgressBar();
            this.materialLabelenemyturn = new MaterialSkin.Controls.MaterialLabel();
            this.materialLabelShipleft = new MaterialSkin.Controls.MaterialLabel();
            this.btnPlay = new System.Windows.Forms.Button();
            this.btnStop = new System.Windows.Forms.Button();
            this.btnRestart = new System.Windows.Forms.Button();
            this.contextMenuStrip.SuspendLayout();
            this.panel.SuspendLayout();
            this.groupBoxEnemy.SuspendLayout();
            this.materialContextMenuStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // button4x
            // 
            this.button4x.Location = new System.Drawing.Point(437, 130);
            this.button4x.Name = "button4x";
            this.button4x.Size = new System.Drawing.Size(47, 23);
            this.button4x.TabIndex = 0;
            this.button4x.Text = "4x";
            this.button4x.UseVisualStyleBackColor = true;
            // 
            // button3x
            // 
            this.button3x.Location = new System.Drawing.Point(490, 130);
            this.button3x.Name = "button3x";
            this.button3x.Size = new System.Drawing.Size(47, 23);
            this.button3x.TabIndex = 1;
            this.button3x.Text = "3x";
            this.button3x.UseVisualStyleBackColor = true;
            // 
            // button2x
            // 
            this.button2x.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.button2x.Location = new System.Drawing.Point(543, 130);
            this.button2x.Name = "button2x";
            this.button2x.Size = new System.Drawing.Size(47, 23);
            this.button2x.TabIndex = 2;
            this.button2x.Text = "2x";
            this.button2x.UseVisualStyleBackColor = true;
            // 
            // button1x
            // 
            this.button1x.Location = new System.Drawing.Point(596, 130);
            this.button1x.Name = "button1x";
            this.button1x.Size = new System.Drawing.Size(47, 23);
            this.button1x.TabIndex = 3;
            this.button1x.Text = "1x";
            this.button1x.UseVisualStyleBackColor = true;
            // 
            // label2x
            // 
            this.label2x.AutoSize = true;
            this.label2x.Location = new System.Drawing.Point(561, 165);
            this.label2x.Name = "label2x";
            this.label2x.Size = new System.Drawing.Size(13, 13);
            this.label2x.TabIndex = 5;
            this.label2x.Text = "3";
            // 
            // label3x
            // 
            this.label3x.AutoSize = true;
            this.label3x.Location = new System.Drawing.Point(507, 165);
            this.label3x.Name = "label3x";
            this.label3x.Size = new System.Drawing.Size(13, 13);
            this.label3x.TabIndex = 6;
            this.label3x.Text = "2";
            // 
            // label4x
            // 
            this.label4x.AutoSize = true;
            this.label4x.Location = new System.Drawing.Point(452, 165);
            this.label4x.Name = "label4x";
            this.label4x.Size = new System.Drawing.Size(13, 13);
            this.label4x.TabIndex = 7;
            this.label4x.Text = "1";
            // 
            // labelYourField
            // 
            this.labelYourField.AutoSize = true;
            this.labelYourField.ForeColor = System.Drawing.Color.Green;
            this.labelYourField.Location = new System.Drawing.Point(129, 72);
            this.labelYourField.Name = "labelYourField";
            this.labelYourField.Size = new System.Drawing.Size(59, 13);
            this.labelYourField.TabIndex = 9;
            this.labelYourField.Text = "Твое поле";
            // 
            // labelEnemyField
            // 
            this.labelEnemyField.AutoSize = true;
            this.labelEnemyField.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.labelEnemyField.Location = new System.Drawing.Point(510, 72);
            this.labelEnemyField.Name = "labelEnemyField";
            this.labelEnemyField.Size = new System.Drawing.Size(91, 13);
            this.labelEnemyField.TabIndex = 10;
            this.labelEnemyField.Text = "Вражеское поле";
            this.labelEnemyField.Visible = false;
            // 
            // labelStatus
            // 
            this.labelStatus.AutoSize = true;
            this.labelStatus.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.labelStatus.Location = new System.Drawing.Point(291, 453);
            this.labelStatus.Name = "labelStatus";
            this.labelStatus.Size = new System.Drawing.Size(90, 20);
            this.labelStatus.TabIndex = 13;
            this.labelStatus.Text = "Статус: ----";
            this.labelStatus.Visible = false;
            // 
            // buttonRestart
            // 
            this.buttonRestart.Location = new System.Drawing.Point(308, 497);
            this.buttonRestart.Name = "buttonRestart";
            this.buttonRestart.Size = new System.Drawing.Size(95, 23);
            this.buttonRestart.TabIndex = 6;
            this.buttonRestart.Text = "Сыграть еще раз";
            this.buttonRestart.UseVisualStyleBackColor = true;
            this.buttonRestart.Visible = false;
            this.buttonRestart.Click += new System.EventHandler(this.ButtonRestart_Click);
            // 
            // labelComputerMove
            // 
            this.labelComputerMove.AutoSize = true;
            this.labelComputerMove.ForeColor = System.Drawing.Color.Red;
            this.labelComputerMove.Location = new System.Drawing.Point(129, 453);
            this.labelComputerMove.Name = "labelComputerMove";
            this.labelComputerMove.Size = new System.Drawing.Size(92, 13);
            this.labelComputerMove.TabIndex = 18;
            this.labelComputerMove.Text = "Ход компьютера";
            this.labelComputerMove.Visible = false;
            this.labelComputerMove.VisibleChanged += new System.EventHandler(this.LabelComputerMove_VisibleChanged);
            // 
            // label1x
            // 
            this.label1x.AutoSize = true;
            this.label1x.Location = new System.Drawing.Point(613, 165);
            this.label1x.Name = "label1x";
            this.label1x.Size = new System.Drawing.Size(13, 13);
            this.label1x.TabIndex = 17;
            this.label1x.Text = "4";
            // 
            // contextMenuStrip
            // 
            this.contextMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.GameRestartToolStripMenuItem,
            this.ComputerMovesSpeedToolStripMenuItem,
            this.MarkComputerMovesToolStripMenuItem});
            this.contextMenuStrip.Name = "contextMenuStrip";
            this.contextMenuStrip.Size = new System.Drawing.Size(201, 70);
            this.contextMenuStrip.Opening += new System.ComponentModel.CancelEventHandler(this.ContextMenuStrip_Opening);
            // 
            // GameRestartToolStripMenuItem
            // 
            this.GameRestartToolStripMenuItem.Name = "GameRestartToolStripMenuItem";
            this.GameRestartToolStripMenuItem.Size = new System.Drawing.Size(200, 22);
            this.GameRestartToolStripMenuItem.Text = "Restart Game";
            this.GameRestartToolStripMenuItem.Click += new System.EventHandler(this.GameRestartToolStripMenuItem_Click);
            // 
            // ComputerMovesSpeedToolStripMenuItem
            // 
            this.ComputerMovesSpeedToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.SlowlyToolStripMenuItem,
            this.AverageToolStripMenuItem,
            this.RapidlyToolStripMenuItem,
            this.InstantlyToolStripMenuItem});
            this.ComputerMovesSpeedToolStripMenuItem.Name = "ComputerMovesSpeedToolStripMenuItem";
            this.ComputerMovesSpeedToolStripMenuItem.Size = new System.Drawing.Size(200, 22);
            this.ComputerMovesSpeedToolStripMenuItem.Text = "Computer moves speed";
            // 
            // SlowlyToolStripMenuItem
            // 
            this.SlowlyToolStripMenuItem.Name = "SlowlyToolStripMenuItem";
            this.SlowlyToolStripMenuItem.Size = new System.Drawing.Size(119, 22);
            this.SlowlyToolStripMenuItem.Text = "Slowly";
            // 
            // AverageToolStripMenuItem
            // 
            this.AverageToolStripMenuItem.Checked = true;
            this.AverageToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.AverageToolStripMenuItem.Name = "AverageToolStripMenuItem";
            this.AverageToolStripMenuItem.Size = new System.Drawing.Size(119, 22);
            this.AverageToolStripMenuItem.Text = "Medium";
            // 
            // RapidlyToolStripMenuItem
            // 
            this.RapidlyToolStripMenuItem.Name = "RapidlyToolStripMenuItem";
            this.RapidlyToolStripMenuItem.Size = new System.Drawing.Size(119, 22);
            this.RapidlyToolStripMenuItem.Text = "Fast";
            // 
            // InstantlyToolStripMenuItem
            // 
            this.InstantlyToolStripMenuItem.Name = "InstantlyToolStripMenuItem";
            this.InstantlyToolStripMenuItem.Size = new System.Drawing.Size(119, 22);
            this.InstantlyToolStripMenuItem.Text = "Instantly";
            // 
            // MarkComputerMovesToolStripMenuItem
            // 
            this.MarkComputerMovesToolStripMenuItem.Checked = true;
            this.MarkComputerMovesToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.MarkComputerMovesToolStripMenuItem.Name = "MarkComputerMovesToolStripMenuItem";
            this.MarkComputerMovesToolStripMenuItem.Size = new System.Drawing.Size(200, 22);
            this.MarkComputerMovesToolStripMenuItem.Text = "Mark computer moves";
            this.MarkComputerMovesToolStripMenuItem.Click += new System.EventHandler(this.MarkComputerMovesToolStripMenuItem_Click);
            // 
            // buttonRotate
            // 
            this.buttonRotate.Location = new System.Drawing.Point(112, 110);
            this.buttonRotate.Name = "buttonRotate";
            this.buttonRotate.Size = new System.Drawing.Size(135, 23);
            this.buttonRotate.TabIndex = 4;
            this.buttonRotate.Text = "Повернуть корабль";
            this.buttonRotate.UseVisualStyleBackColor = true;
            this.buttonRotate.Click += new System.EventHandler(this.ButtonRotate_Click);
            // 
            // comboBoxComputerMoveSpeed
            // 
            this.comboBoxComputerMoveSpeed.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.comboBoxComputerMoveSpeed.FormattingEnabled = true;
            this.comboBoxComputerMoveSpeed.Items.AddRange(new object[] {
            "Медленная",
            "Средняя",
            "Быстрая",
            "Мгновенная"});
            this.comboBoxComputerMoveSpeed.Location = new System.Drawing.Point(35, 42);
            this.comboBoxComputerMoveSpeed.Name = "comboBoxComputerMoveSpeed";
            this.comboBoxComputerMoveSpeed.Size = new System.Drawing.Size(135, 21);
            this.comboBoxComputerMoveSpeed.TabIndex = 15;
            this.comboBoxComputerMoveSpeed.SelectedIndexChanged += new System.EventHandler(this.ComboBox_SelectedIndexChanged);
            // 
            // buttonGameStart
            // 
            this.buttonGameStart.Enabled = false;
            this.buttonGameStart.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.buttonGameStart.Location = new System.Drawing.Point(112, 362);
            this.buttonGameStart.Name = "buttonGameStart";
            this.buttonGameStart.Size = new System.Drawing.Size(135, 23);
            this.buttonGameStart.TabIndex = 5;
            this.buttonGameStart.Text = "Начать игру";
            this.buttonGameStart.UseVisualStyleBackColor = true;
            this.buttonGameStart.Click += new System.EventHandler(this.ButtonGameStart_Click);
            // 
            // labelShipsPlaceLeft
            // 
            this.labelShipsPlaceLeft.AutoSize = true;
            this.labelShipsPlaceLeft.BackColor = System.Drawing.Color.Transparent;
            this.labelShipsPlaceLeft.Location = new System.Drawing.Point(85, 479);
            this.labelShipsPlaceLeft.Name = "labelShipsPlaceLeft";
            this.labelShipsPlaceLeft.Size = new System.Drawing.Size(115, 13);
            this.labelShipsPlaceLeft.TabIndex = 14;
            this.labelShipsPlaceLeft.Text = "Оставшиеся корабли";
            // 
            // labelPlaceShips
            // 
            this.labelPlaceShips.AutoSize = true;
            this.labelPlaceShips.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.labelPlaceShips.Location = new System.Drawing.Point(71, 10);
            this.labelPlaceShips.Name = "labelPlaceShips";
            this.labelPlaceShips.Size = new System.Drawing.Size(181, 20);
            this.labelPlaceShips.TabIndex = 15;
            this.labelPlaceShips.Text = "Размещение кораблей";
            // 
            // progressBar
            // 
            this.progressBar.Location = new System.Drawing.Point(62, 471);
            this.progressBar.Name = "progressBar";
            this.progressBar.Size = new System.Drawing.Size(159, 23);
            this.progressBar.TabIndex = 11;
            // 
            // labelComputerMovingSpeed
            // 
            this.labelComputerMovingSpeed.AutoSize = true;
            this.labelComputerMovingSpeed.Location = new System.Drawing.Point(67, 26);
            this.labelComputerMovingSpeed.Name = "labelComputerMovingSpeed";
            this.labelComputerMovingSpeed.Size = new System.Drawing.Size(81, 13);
            this.labelComputerMovingSpeed.TabIndex = 16;
            this.labelComputerMovingSpeed.Text = "Скорость хода";
            // 
            // panel
            // 
            this.panel.BackColor = System.Drawing.SystemColors.Control;
            this.panel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.panel.Controls.Add(this.materialLabelPlace);
            this.panel.Controls.Add(this.RaisedButtonRotate);
            this.panel.Controls.Add(this.FlatButtonRotate);
            this.panel.Controls.Add(this.RandomArangeShip);
            this.panel.Controls.Add(this.materialLabelplaceship);
            this.panel.Controls.Add(this.groupBoxEnemy);
            this.panel.Controls.Add(this.buttonArrangeShipsRandomly);
            this.panel.Controls.Add(this.labelPlaceShips);
            this.panel.Controls.Add(this.buttonGameStart);
            this.panel.Controls.Add(this.buttonRotate);
            this.panel.Location = new System.Drawing.Point(387, 88);
            this.panel.Name = "panel";
            this.panel.Size = new System.Drawing.Size(330, 404);
            this.panel.TabIndex = 19;
            // 
            // materialLabelPlace
            // 
            this.materialLabelPlace.AutoSize = true;
            this.materialLabelPlace.Depth = 0;
            this.materialLabelPlace.Font = new System.Drawing.Font("Roboto", 11F);
            this.materialLabelPlace.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.materialLabelPlace.Location = new System.Drawing.Point(108, 136);
            this.materialLabelPlace.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialLabelPlace.Name = "materialLabelPlace";
            this.materialLabelPlace.Size = new System.Drawing.Size(127, 19);
            this.materialLabelPlace.TabIndex = 27;
            this.materialLabelPlace.Text = "Расположение: |";
            // 
            // RaisedButtonRotate
            // 
            this.RaisedButtonRotate.AutoSize = true;
            this.RaisedButtonRotate.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.RaisedButtonRotate.Depth = 0;
            this.RaisedButtonRotate.Icon = null;
            this.RaisedButtonRotate.Location = new System.Drawing.Point(93, 97);
            this.RaisedButtonRotate.MouseState = MaterialSkin.MouseState.HOVER;
            this.RaisedButtonRotate.Name = "RaisedButtonRotate";
            this.RaisedButtonRotate.Primary = true;
            this.RaisedButtonRotate.Size = new System.Drawing.Size(167, 36);
            this.RaisedButtonRotate.TabIndex = 26;
            this.RaisedButtonRotate.Text = "Повернуть корабль";
            this.RaisedButtonRotate.UseVisualStyleBackColor = true;
            this.RaisedButtonRotate.Click += new System.EventHandler(this.ButtonRotate_Click);
            // 
            // FlatButtonRotate
            // 
            this.FlatButtonRotate.AutoSize = true;
            this.FlatButtonRotate.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.FlatButtonRotate.Depth = 0;
            this.FlatButtonRotate.Icon = null;
            this.FlatButtonRotate.Location = new System.Drawing.Point(93, 103);
            this.FlatButtonRotate.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.FlatButtonRotate.MouseState = MaterialSkin.MouseState.HOVER;
            this.FlatButtonRotate.Name = "FlatButtonRotate";
            this.FlatButtonRotate.Primary = false;
            this.FlatButtonRotate.Size = new System.Drawing.Size(167, 36);
            this.FlatButtonRotate.TabIndex = 25;
            this.FlatButtonRotate.Text = "Повернуть корабль";
            this.FlatButtonRotate.UseVisualStyleBackColor = true;
            this.FlatButtonRotate.Click += new System.EventHandler(this.ButtonRotate_Click);
            // 
            // RandomArangeShip
            // 
            this.RandomArangeShip.AutoSize = true;
            this.RandomArangeShip.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.RandomArangeShip.Depth = 0;
            this.RandomArangeShip.Icon = null;
            this.RandomArangeShip.Location = new System.Drawing.Point(112, 161);
            this.RandomArangeShip.MouseState = MaterialSkin.MouseState.HOVER;
            this.RandomArangeShip.Name = "RandomArangeShip";
            this.RandomArangeShip.Primary = true;
            this.RandomArangeShip.Size = new System.Drawing.Size(118, 36);
            this.RandomArangeShip.TabIndex = 24;
            this.RandomArangeShip.Text = "Случайная \r\nрасстановка";
            this.RandomArangeShip.UseVisualStyleBackColor = true;
            this.RandomArangeShip.Click += new System.EventHandler(this.ButtonArrangeShipsRandomly_Click);
            // 
            // materialLabelplaceship
            // 
            this.materialLabelplaceship.AutoSize = true;
            this.materialLabelplaceship.Depth = 0;
            this.materialLabelplaceship.Font = new System.Drawing.Font("Roboto", 14F);
            this.materialLabelplaceship.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.materialLabelplaceship.Location = new System.Drawing.Point(77, 10);
            this.materialLabelplaceship.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialLabelplaceship.Name = "materialLabelplaceship";
            this.materialLabelplaceship.Size = new System.Drawing.Size(170, 19);
            this.materialLabelplaceship.TabIndex = 23;
            this.materialLabelplaceship.Text = "Размещение кораблей";
            // 
            // groupBoxEnemy
            // 
            this.groupBoxEnemy.BackColor = System.Drawing.SystemColors.Control;
            this.groupBoxEnemy.Controls.Add(this.checkrandommoves);
            this.groupBoxEnemy.Controls.Add(this.checkBoxEnemyRandomMoves);
            this.groupBoxEnemy.Controls.Add(this.labelComputerMovingSpeed);
            this.groupBoxEnemy.Controls.Add(this.MarkenemyMoves);
            this.groupBoxEnemy.Controls.Add(this.comboBoxComputerMoveSpeed);
            this.groupBoxEnemy.Location = new System.Drawing.Point(77, 217);
            this.groupBoxEnemy.Name = "groupBoxEnemy";
            this.groupBoxEnemy.Size = new System.Drawing.Size(200, 126);
            this.groupBoxEnemy.TabIndex = 21;
            this.groupBoxEnemy.TabStop = false;
            this.groupBoxEnemy.Text = "Вражеский компьютер";
            // 
            // checkrandommoves
            // 
            this.checkrandommoves.AutoSize = true;
            this.checkrandommoves.Depth = 0;
            this.checkrandommoves.Font = new System.Drawing.Font("Roboto", 10F);
            this.checkrandommoves.Location = new System.Drawing.Point(37, 93);
            this.checkrandommoves.Margin = new System.Windows.Forms.Padding(0);
            this.checkrandommoves.MouseLocation = new System.Drawing.Point(-1, -1);
            this.checkrandommoves.MouseState = MaterialSkin.MouseState.HOVER;
            this.checkrandommoves.Name = "checkrandommoves";
            this.checkrandommoves.Ripple = true;
            this.checkrandommoves.Size = new System.Drawing.Size(138, 30);
            this.checkrandommoves.TabIndex = 28;
            this.checkrandommoves.Text = "Случайные шаги";
            this.checkrandommoves.UseVisualStyleBackColor = true;
            // 
            // checkBoxEnemyRandomMoves
            // 
            this.checkBoxEnemyRandomMoves.AutoSize = true;
            this.checkBoxEnemyRandomMoves.Location = new System.Drawing.Point(56, 103);
            this.checkBoxEnemyRandomMoves.Name = "checkBoxEnemyRandomMoves";
            this.checkBoxEnemyRandomMoves.Size = new System.Drawing.Size(109, 17);
            this.checkBoxEnemyRandomMoves.TabIndex = 20;
            this.checkBoxEnemyRandomMoves.Text = "Случайные шаги";
            this.checkBoxEnemyRandomMoves.UseVisualStyleBackColor = true;
            // 
            // MarkenemyMoves
            // 
            this.MarkenemyMoves.AutoSize = true;
            this.MarkenemyMoves.BackColor = System.Drawing.SystemColors.Control;
            this.MarkenemyMoves.Checked = true;
            this.MarkenemyMoves.CheckState = System.Windows.Forms.CheckState.Checked;
            this.MarkenemyMoves.Depth = 0;
            this.MarkenemyMoves.Font = new System.Drawing.Font("Roboto", 10F);
            this.MarkenemyMoves.Location = new System.Drawing.Point(37, 66);
            this.MarkenemyMoves.Margin = new System.Windows.Forms.Padding(0);
            this.MarkenemyMoves.MouseLocation = new System.Drawing.Point(-1, -1);
            this.MarkenemyMoves.MouseState = MaterialSkin.MouseState.HOVER;
            this.MarkenemyMoves.Name = "MarkenemyMoves";
            this.MarkenemyMoves.Ripple = true;
            this.MarkenemyMoves.Size = new System.Drawing.Size(130, 30);
            this.MarkenemyMoves.TabIndex = 25;
            this.MarkenemyMoves.Text = "Помечать шаги";
            this.MarkenemyMoves.UseVisualStyleBackColor = false;
            this.MarkenemyMoves.CheckedChanged += new System.EventHandler(this.CheckBoxMarkEnemyMoves_CheckedChanged);
            // 
            // buttonArrangeShipsRandomly
            // 
            this.buttonArrangeShipsRandomly.Location = new System.Drawing.Point(146, 169);
            this.buttonArrangeShipsRandomly.Name = "buttonArrangeShipsRandomly";
            this.buttonArrangeShipsRandomly.Size = new System.Drawing.Size(62, 20);
            this.buttonArrangeShipsRandomly.TabIndex = 22;
            this.buttonArrangeShipsRandomly.Text = "Случайная растанновка";
            this.buttonArrangeShipsRandomly.UseVisualStyleBackColor = true;
            this.buttonArrangeShipsRandomly.Click += new System.EventHandler(this.ButtonArrangeShipsRandomly_Click);
            // 
            // labelPrompt
            // 
            this.labelPrompt.AutoSize = true;
            this.labelPrompt.BackColor = System.Drawing.SystemColors.Control;
            this.labelPrompt.ForeColor = System.Drawing.SystemColors.ControlDark;
            this.labelPrompt.Location = new System.Drawing.Point(561, 539);
            this.labelPrompt.Name = "labelPrompt";
            this.labelPrompt.Size = new System.Drawing.Size(180, 13);
            this.labelPrompt.TabIndex = 20;
            this.labelPrompt.Text = "правый клик для смены настроек";
            // 
            // materialContextMenuStrip1
            // 
            this.materialContextMenuStrip1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.materialContextMenuStrip1.Depth = 0;
            this.materialContextMenuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.перезапуститьИгруToolStripMenuItem,
            this.скоростьХодаКомпьютераToolStripMenuItem,
            this.помечатьШагиToolStripMenuItem,
            this.выходToolStripMenuItem});
            this.materialContextMenuStrip1.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialContextMenuStrip1.Name = "materialContextMenuStrip1";
            this.materialContextMenuStrip1.Size = new System.Drawing.Size(226, 92);
            this.materialContextMenuStrip1.Opening += new System.ComponentModel.CancelEventHandler(this.materialContextMenuStrip1_Opening);
            // 
            // перезапуститьИгруToolStripMenuItem
            // 
            this.перезапуститьИгруToolStripMenuItem.Name = "перезапуститьИгруToolStripMenuItem";
            this.перезапуститьИгруToolStripMenuItem.Size = new System.Drawing.Size(225, 22);
            this.перезапуститьИгруToolStripMenuItem.Text = "Перезапустить игру";
            this.перезапуститьИгруToolStripMenuItem.Click += new System.EventHandler(this.перезапуститьИгруToolStripMenuItem_Click);
            // 
            // скоростьХодаКомпьютераToolStripMenuItem
            // 
            this.скоростьХодаКомпьютераToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.медленнаяToolStripMenuItem,
            this.средняяToolStripMenuItem,
            this.быстраяToolStripMenuItem,
            this.мгновеннаяToolStripMenuItem});
            this.скоростьХодаКомпьютераToolStripMenuItem.Name = "скоростьХодаКомпьютераToolStripMenuItem";
            this.скоростьХодаКомпьютераToolStripMenuItem.Size = new System.Drawing.Size(225, 22);
            this.скоростьХодаКомпьютераToolStripMenuItem.Text = "Скорость хода компьютера";
            // 
            // медленнаяToolStripMenuItem
            // 
            this.медленнаяToolStripMenuItem.Name = "медленнаяToolStripMenuItem";
            this.медленнаяToolStripMenuItem.Size = new System.Drawing.Size(142, 22);
            this.медленнаяToolStripMenuItem.Text = "Медленная";
            // 
            // средняяToolStripMenuItem
            // 
            this.средняяToolStripMenuItem.Checked = true;
            this.средняяToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.средняяToolStripMenuItem.Name = "средняяToolStripMenuItem";
            this.средняяToolStripMenuItem.Size = new System.Drawing.Size(142, 22);
            this.средняяToolStripMenuItem.Text = "Средняя";
            // 
            // быстраяToolStripMenuItem
            // 
            this.быстраяToolStripMenuItem.Name = "быстраяToolStripMenuItem";
            this.быстраяToolStripMenuItem.Size = new System.Drawing.Size(142, 22);
            this.быстраяToolStripMenuItem.Text = "Быстрая";
            // 
            // мгновеннаяToolStripMenuItem
            // 
            this.мгновеннаяToolStripMenuItem.Name = "мгновеннаяToolStripMenuItem";
            this.мгновеннаяToolStripMenuItem.Size = new System.Drawing.Size(142, 22);
            this.мгновеннаяToolStripMenuItem.Text = "Мгновенная";
            // 
            // помечатьШагиToolStripMenuItem
            // 
            this.помечатьШагиToolStripMenuItem.Checked = true;
            this.помечатьШагиToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.помечатьШагиToolStripMenuItem.Name = "помечатьШагиToolStripMenuItem";
            this.помечатьШагиToolStripMenuItem.Size = new System.Drawing.Size(225, 22);
            this.помечатьШагиToolStripMenuItem.Text = "Помечать шаги";
            this.помечатьШагиToolStripMenuItem.Click += new System.EventHandler(this.помечатьШагиToolStripMenuItem_Click);
            // 
            // выходToolStripMenuItem
            // 
            this.выходToolStripMenuItem.Name = "выходToolStripMenuItem";
            this.выходToolStripMenuItem.Size = new System.Drawing.Size(225, 22);
            this.выходToolStripMenuItem.Text = "Выход";
            this.выходToolStripMenuItem.Click += new System.EventHandler(this.выходToolStripMenuItem_Click);
            // 
            // materialLabelyourfield
            // 
            this.materialLabelyourfield.AutoSize = true;
            this.materialLabelyourfield.BackColor = System.Drawing.Color.Transparent;
            this.materialLabelyourfield.Depth = 0;
            this.materialLabelyourfield.Font = new System.Drawing.Font("Roboto", 11F);
            this.materialLabelyourfield.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.materialLabelyourfield.Location = new System.Drawing.Point(117, 66);
            this.materialLabelyourfield.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialLabelyourfield.Name = "materialLabelyourfield";
            this.materialLabelyourfield.Size = new System.Drawing.Size(83, 19);
            this.materialLabelyourfield.TabIndex = 21;
            this.materialLabelyourfield.Text = "Твое поле";
            // 
            // materialSingleLineTextField1
            // 
            this.materialSingleLineTextField1.Depth = 0;
            this.materialSingleLineTextField1.Enabled = false;
            this.materialSingleLineTextField1.Hint = "";
            this.materialSingleLineTextField1.Location = new System.Drawing.Point(499, 529);
            this.materialSingleLineTextField1.MaxLength = 32767;
            this.materialSingleLineTextField1.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialSingleLineTextField1.Name = "materialSingleLineTextField1";
            this.materialSingleLineTextField1.PasswordChar = '\0';
            this.materialSingleLineTextField1.SelectedText = "";
            this.materialSingleLineTextField1.SelectionLength = 0;
            this.materialSingleLineTextField1.SelectionStart = 0;
            this.materialSingleLineTextField1.Size = new System.Drawing.Size(249, 23);
            this.materialSingleLineTextField1.TabIndex = 22;
            this.materialSingleLineTextField1.TabStop = false;
            this.materialSingleLineTextField1.Text = "правый клик для смены настроек";
            this.materialSingleLineTextField1.UseSystemPasswordChar = false;
            // 
            // materialLabelenemyField
            // 
            this.materialLabelenemyField.AutoSize = true;
            this.materialLabelenemyField.BackColor = System.Drawing.Color.Transparent;
            this.materialLabelenemyField.Depth = 0;
            this.materialLabelenemyField.Font = new System.Drawing.Font("Roboto", 11F);
            this.materialLabelenemyField.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.materialLabelenemyField.Location = new System.Drawing.Point(488, 66);
            this.materialLabelenemyField.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialLabelenemyField.Name = "materialLabelenemyField";
            this.materialLabelenemyField.Size = new System.Drawing.Size(125, 19);
            this.materialLabelenemyField.TabIndex = 23;
            this.materialLabelenemyField.Text = "Вражеское поле";
            this.materialLabelenemyField.Visible = false;
            // 
            // materialButtonRestart
            // 
            this.materialButtonRestart.AutoSize = true;
            this.materialButtonRestart.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.materialButtonRestart.Depth = 0;
            this.materialButtonRestart.Icon = null;
            this.materialButtonRestart.Location = new System.Drawing.Point(295, 497);
            this.materialButtonRestart.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialButtonRestart.Name = "materialButtonRestart";
            this.materialButtonRestart.Primary = true;
            this.materialButtonRestart.Size = new System.Drawing.Size(117, 36);
            this.materialButtonRestart.TabIndex = 24;
            this.materialButtonRestart.Text = "Сыграть еще";
            this.materialButtonRestart.UseVisualStyleBackColor = true;
            this.materialButtonRestart.Visible = false;
            this.materialButtonRestart.Click += new System.EventHandler(this.materialButtonRestart_Click);
            // 
            // materialProgressBar1
            // 
            this.materialProgressBar1.Depth = 0;
            this.materialProgressBar1.Location = new System.Drawing.Point(62, 497);
            this.materialProgressBar1.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialProgressBar1.Name = "materialProgressBar1";
            this.materialProgressBar1.Size = new System.Drawing.Size(159, 5);
            this.materialProgressBar1.TabIndex = 25;
            // 
            // materialLabelenemyturn
            // 
            this.materialLabelenemyturn.AutoSize = true;
            this.materialLabelenemyturn.Depth = 0;
            this.materialLabelenemyturn.Font = new System.Drawing.Font("Roboto", 11F);
            this.materialLabelenemyturn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.materialLabelenemyturn.Location = new System.Drawing.Point(116, 449);
            this.materialLabelenemyturn.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialLabelenemyturn.Name = "materialLabelenemyturn";
            this.materialLabelenemyturn.Size = new System.Drawing.Size(128, 19);
            this.materialLabelenemyturn.TabIndex = 26;
            this.materialLabelenemyturn.Text = "Ход компьютера";
            this.materialLabelenemyturn.Visible = false;
            this.materialLabelenemyturn.VisibleChanged += new System.EventHandler(this.LabelComputerMove_VisibleChanged);
            // 
            // materialLabelShipleft
            // 
            this.materialLabelShipleft.AutoSize = true;
            this.materialLabelShipleft.Depth = 0;
            this.materialLabelShipleft.Font = new System.Drawing.Font("Roboto", 11F);
            this.materialLabelShipleft.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.materialLabelShipleft.Location = new System.Drawing.Point(62, 473);
            this.materialLabelShipleft.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialLabelShipleft.Name = "materialLabelShipleft";
            this.materialLabelShipleft.Size = new System.Drawing.Size(159, 19);
            this.materialLabelShipleft.TabIndex = 27;
            this.materialLabelShipleft.Text = "Оставшиеся корабли";
            // 
            // btnPlay
            // 
            this.btnPlay.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPlay.BackgroundImage")));
            this.btnPlay.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnPlay.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPlay.Location = new System.Drawing.Point(30, 513);
            this.btnPlay.Name = "btnPlay";
            this.btnPlay.Size = new System.Drawing.Size(45, 44);
            this.btnPlay.TabIndex = 28;
            this.btnPlay.UseVisualStyleBackColor = true;
            this.btnPlay.Click += new System.EventHandler(this.btnPlay_Click);
            // 
            // btnStop
            // 
            this.btnStop.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnStop.BackgroundImage")));
            this.btnStop.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnStop.Location = new System.Drawing.Point(81, 513);
            this.btnStop.Name = "btnStop";
            this.btnStop.Size = new System.Drawing.Size(47, 44);
            this.btnStop.TabIndex = 29;
            this.btnStop.UseVisualStyleBackColor = true;
            this.btnStop.Click += new System.EventHandler(this.btnStop_Click);
            // 
            // btnRestart
            // 
            this.btnRestart.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRestart.BackgroundImage")));
            this.btnRestart.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnRestart.Location = new System.Drawing.Point(134, 513);
            this.btnRestart.Name = "btnRestart";
            this.btnRestart.Size = new System.Drawing.Size(47, 44);
            this.btnRestart.TabIndex = 30;
            this.btnRestart.UseVisualStyleBackColor = true;
            this.btnRestart.Click += new System.EventHandler(this.btnRestart_Click);
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(780, 577);
            this.ContextMenuStrip = this.materialContextMenuStrip1;
            this.Controls.Add(this.btnRestart);
            this.Controls.Add(this.btnStop);
            this.Controls.Add(this.btnPlay);
            this.Controls.Add(this.materialLabelShipleft);
            this.Controls.Add(this.materialLabelenemyturn);
            this.Controls.Add(this.materialProgressBar1);
            this.Controls.Add(this.materialButtonRestart);
            this.Controls.Add(this.materialLabelenemyField);
            this.Controls.Add(this.materialSingleLineTextField1);
            this.Controls.Add(this.materialLabelyourfield);
            this.Controls.Add(this.labelPrompt);
            this.Controls.Add(this.label1x);
            this.Controls.Add(this.labelComputerMove);
            this.Controls.Add(this.labelShipsPlaceLeft);
            this.Controls.Add(this.buttonRestart);
            this.Controls.Add(this.labelStatus);
            this.Controls.Add(this.labelEnemyField);
            this.Controls.Add(this.progressBar);
            this.Controls.Add(this.labelYourField);
            this.Controls.Add(this.label4x);
            this.Controls.Add(this.label3x);
            this.Controls.Add(this.label2x);
            this.Controls.Add(this.button1x);
            this.Controls.Add(this.button2x);
            this.Controls.Add(this.button3x);
            this.Controls.Add(this.button4x);
            this.Controls.Add(this.panel);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Sea battle";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.contextMenuStrip.ResumeLayout(false);
            this.panel.ResumeLayout(false);
            this.panel.PerformLayout();
            this.groupBoxEnemy.ResumeLayout(false);
            this.groupBoxEnemy.PerformLayout();
            this.materialContextMenuStrip1.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button button4x;
        private System.Windows.Forms.Button button3x;
        private System.Windows.Forms.Button button2x;
        private System.Windows.Forms.Button button1x;
        private System.Windows.Forms.Label label2x;
        private System.Windows.Forms.Label label3x;
        private System.Windows.Forms.Label label4x;
        private System.Windows.Forms.Label labelYourField;
        private System.Windows.Forms.Label labelEnemyField;
        private System.Windows.Forms.Label labelStatus;
        private System.Windows.Forms.Button buttonRestart;
        private System.Windows.Forms.Label labelComputerMove;
        private System.Windows.Forms.Label label1x;
        private System.Windows.Forms.ContextMenuStrip contextMenuStrip;
        private System.Windows.Forms.ToolStripMenuItem GameRestartToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ComputerMovesSpeedToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem SlowlyToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem AverageToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem RapidlyToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem InstantlyToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem MarkComputerMovesToolStripMenuItem;
        private System.Windows.Forms.Button buttonRotate;
        private System.Windows.Forms.ComboBox comboBoxComputerMoveSpeed;
        private System.Windows.Forms.Button buttonGameStart;
        private System.Windows.Forms.Label labelShipsPlaceLeft;
        private System.Windows.Forms.Label labelPlaceShips;
        private System.Windows.Forms.ProgressBar progressBar;
        private System.Windows.Forms.Label labelComputerMovingSpeed;
        private System.Windows.Forms.Panel panel;
        private System.Windows.Forms.CheckBox checkBoxEnemyRandomMoves;
        private System.Windows.Forms.GroupBox groupBoxEnemy;
        private System.Windows.Forms.Button buttonArrangeShipsRandomly;
        private System.Windows.Forms.Label labelPrompt;
        private MaterialSkin.Controls.MaterialContextMenuStrip materialContextMenuStrip1;
        private System.Windows.Forms.ToolStripMenuItem перезапуститьИгруToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem скоростьХодаКомпьютераToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem помечатьШагиToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem выходToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem медленнаяToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem средняяToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem быстраяToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem мгновеннаяToolStripMenuItem;
        private MaterialSkin.Controls.MaterialLabel materialLabelyourfield;
        private MaterialSkin.Controls.MaterialSingleLineTextField materialSingleLineTextField1;
        private MaterialSkin.Controls.MaterialLabel materialLabelenemyField;
        private MaterialSkin.Controls.MaterialRaisedButton materialButtonRestart;
        private MaterialSkin.Controls.MaterialLabel materialLabelplaceship;
        private MaterialSkin.Controls.MaterialProgressBar materialProgressBar1;
        private MaterialSkin.Controls.MaterialLabel materialLabelenemyturn;
        private MaterialSkin.Controls.MaterialRaisedButton RandomArangeShip;
        private MaterialSkin.Controls.MaterialCheckBox MarkenemyMoves;
        private MaterialSkin.Controls.MaterialFlatButton FlatButtonRotate;
        private MaterialSkin.Controls.MaterialLabel materialLabelShipleft;
        private MaterialSkin.Controls.MaterialCheckBox checkrandommoves;
        private MaterialSkin.Controls.MaterialRaisedButton RaisedButtonRotate;
        private MaterialSkin.Controls.MaterialLabel materialLabelPlace;
        private System.Windows.Forms.Button btnPlay;
        private System.Windows.Forms.Button btnStop;
        private System.Windows.Forms.Button btnRestart;
    }
}